backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'cennik'
    label: 'Cennik'
    folder: 'content/cennik'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Nazwa usługi', name: 'name', widget: 'string' }
      - { label: 'Dolny próg cenowy', name: 'min_price', widget: 'string' }
      - { label: 'Górny próg cenowy', name: 'max_price', widget: 'string' }
      - { 
          label: 'Sztuka / Zestaw', 
          name: 'quantity_type', 
          widget: 'select',
          options: ["sztuka", "zestaw"] 
        }