backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /src/images/uploads

collections:
  - name: 'cennik'
    label: 'Cennik'
    folder: 'content/cennik'
    create: true
    editor:
      preview: false
    sort: 'min_price:asc'
    fields:
      - { label: 'Nazwa usługi', name: 'name', widget: 'string' }
      - { label: 'Dolny próg cenowy', name: 'min_price', widget: 'string' }
      - { label: 'Górny próg cenowy', name: 'max_price', widget: 'string' }
      - { 
          label: 'Sztuka / Zestaw', 
          name: 'quantity_type', 
          widget: 'select',
          options: ["sztuka", "zestaw"],
          default: ["sztuka"]
        }
  - name: 'oferta'
    label: 'Oferta'
    folder: 'content/oferta'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: false
    sort: ''
    fields:
      - { label: 'Tytuł oferty', name: 'title', widget: 'string' }
      - { label: 'Podtytuł oferty / krótki wstęp', name: 'subtitle', widget: 'text' }
      - { 
          label: 'Data dodania', 
          name: 'publish_date', 
          widget: 'datetime',
          default: '',
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm" 
        }
      - { 
          label: 'Zdjęcie główne', 
          name: 'hero_pic', 
          widget: 'image',
          choose_url: true,
        }
      - { label: 'Opis oferty', name: 'body', widget: 'markdown' }
  # - name: 'galeria'
  #   label: 'Galeria'
  #   folder: 'content/galeria'
  #   create: true
  #   fields:
  #       - { 
  #           label: 'Zdjęcia w galerii',
  #           name: 'images',
  #           widget: 'modular',
  #           types: 
  #             - { label: 'image', name: 'image', widget: 'image', choose_url: true }
  #        }
    